[package]
name = "joint_sim"
version = "0.1.0"
edition = "2021"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.0", features = ["dynamic_linking"] }
bevy_rapier2d = "0.22.0"
bevy-inspector-egui = "0.19.0"
bevy-inspector-egui-rapier = "0.9.0"
bevy_prototype_lyon = "0.9.0"
serde = "1.0.163"
serde_json = "1.0.96"
bevy-trait-query = "0.3.0"
nalgebra = "0.32.3"
rand = "0.8.5"
