[package]
name = "joint_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy_rapier2d = "0.22.0"
bevy-inspector-egui = "0.19.0"
bevy-inspector-egui-rapier = "0.9.0"
bevy_prototype_lyon = "0.9.0"
serde = "1.0.163"
serde_json = "1.0.96"
bevy-trait-query = "0.3.0"
