[package]
name = "joint_sim"
version = "0.2.0"
edition = "2021"
resolver = "2"

# Enable a small amount of optimization in debug mode
[profile.dev]
codegen-units = 1
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
[profile.dev.package.bevy_rapier2d]
opt-level = 3

# [target.x86_64-pc-windows-msvc]
# rustflags = ["-Ctarget-feature=+crt-static"]
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = "0.11.0"
# leak-detect-allocator = { git = "https://github.com/lynnux/leak-detect-allocator.git" }
# bevy = { version = "0.11.0", features = ["dynamic_linking"] }
wasm-bindgen = "0.2.87"
bevy_rapier2d = { version = "0.22.0", features = ["wasm-bindgen"] }
bevy-inspector-egui = "0.19.0"
bevy-inspector-egui-rapier = "0.9.0"
serde = "1.0.163"
serde_json = "1.0.96"
nalgebra = "0.32.3"
rand = "0.8.5"
chrono = "0.4.28"


# # Dependencies for native only.
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# bevy = { version = "0.11.0", default-features = false, features = [
#     "bevy_winit",
#     "render",
#     "x11",
# ] }

# # Dependencies for WASM only.
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# bevy = { version = "0.11.0", default-features = false, features = [
#     "bevy_winit",
#     "render",
# ] }
# bevy_webgl2 = "0.5.2"
